### ISSUE TITLE
Failed to parse floating value for used_cpu

### ISSUE THREAD

**Issue by RedWhiteMiko** [powdahound/redis-collectd-plugin#17]
When putting the value with floating point, the redis_info.py throw an error
example value:  
- used_cpu_sys
- used_cpu_user

```
[2015-08-11 03:01:53] Unhandled python exception in read callback: ValueError: invalid literal for int() with base 10: '88.13'
[2015-08-11 03:01:53] Traceback (most recent call last):
[2015-08-11 03:01:53]   File "/etc/collectd.d/redis_info.py", line 177, in read_callback
    get_metrics( conf )
[2015-08-11 03:01:53]   File "/etc/collectd.d/redis_info.py", line 197, in get_metrics
    dispatch_value(info, key, val, plugin_instance)
[2015-08-11 03:01:53]   File "/etc/collectd.d/redis_info.py", line 165, in dispatch_value
    value = int(info[key])
[2015-08-11 03:01:53] ValueError: invalid literal for int() with base 10: '88.13'
[2015-08-11 03:01:53] read-function of plugin `python.redis_info' failed. Will suspend it for 120.000 seconds.
[2015-08-11 03:03:53] Unhandled python exception in read callback: ValueError: invalid literal for int() with base 10: '88.16'
[2015-08-11 03:03:53] Traceback (most recent call last):
[2015-08-11 03:03:53]   File "/etc/collectd.d/redis_info.py", line 177, in read_callback
    get_metrics( conf )
[2015-08-11 03:03:53]   File "/etc/collectd.d/redis_info.py", line 197, in get_metrics
    dispatch_value(info, key, val, plugin_instance)
[2015-08-11 03:03:53]   File "/etc/collectd.d/redis_info.py", line 165, in dispatch_value
    value = int(info[key])
[2015-08-11 03:03:53] ValueError: invalid literal for int() with base 10: '88.16'
[2015-08-11 03:03:53] read-function of plugin `python.redis_info' failed. Will suspend it for 240.000 seconds.
[2015-08-11 03:06:56] Exiting normally.
[2015-08-11 03:06:56] collectd: Stopping 5 read threads.
[2015-08-11 03:06:56] collectd: Stopping 5 write threads.
[2015-08-11 03:06:59] Initialization complete, entering read-loop.
```

**Comment by powdahound** [comment]
Interesting... did a new Redis version just begin to send non-int values?
